### ISSUE TITLE
Feature / Capability matrix rough draft

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#1]
AC
- [x] Review vision for total scope of KPCC needs  
- [x] Review station research feedback
- [x] Create a rough draft matrix for features / capabilities

**Comment by sdillingham** [comment]
First pass at a Digital Audio Workflow Matrix lives here:

https://docs.google.com/spreadsheets/d/153NWXadFuMpyrFqbTyEuH4oyH-yms_6PkoIcKRcn34g/edit#gid=0
