### ISSUE TITLE
Sketch out a plan for a direct connection between Resound and Outpost

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#135]
AC

- [x] Document a plan for a direct connection between Resound and Outpost

**Comment by nakedsushi** [comment]
Alright, check it out:

The user comes into outpost and starts a new story.  When they scroll down to the audio section, there's a new tab for Resound.  Clicking on that tab shows a link that will open Resound in a separate window.
<img width="883" alt="resound_in_outpost" src="https://user-images.githubusercontent.com/360040/32021666-d37e803e-b988-11e7-8476-74ac3d8993a5.png">

In Resound Store, they can search for the audio they want, click to the audio page. If they had come thru outpost, there will be a new column or icon (maybe some arrow thing to denote "send"). Clicking on the icon will automagically send that link to the URL field in outpost via postmessage. Ideally, this only in our case (where we have outpost integration turned on). @tinykb thoughts on how this should look?
<img width="1002" alt="resound_send_to_outpost" src="https://user-images.githubusercontent.com/360040/32021670-d8890bd0-b988-11e7-8fba-8cffac7affb6.png">

**Comment by nakedsushi** [comment]
Pending design thoughts from Katie.
