### ISSUE TITLE
Bug: Successfully uploaded file cut-off end of audio

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#160]
This entry originally had the audio cut off at 24:43: http://resound-store.scprdev.org/audio/130-WeTransfer_art,_Hannah_Gadsby,_student_jazz_bassist

Note: the time reported by Resound was correct for the cutoff version of the file, but the original wav was 28:04

**Comment by nakedsushi** [comment]
Never came back, so not gonna fix it since we're moving off of Resound anyway.
