### ISSUE TITLE
Add dotenv support to Resound store-upload

### ISSUE THREAD

**Issue by nakedsushi** [ProjectLoudly/planning#166]
AC:
- [x] there is dotenv support in the react project
- [x] there is documentation or an example of what to put in dotenv
- [x] release to kpcc instance
- [ ] update latest docker image

**Comment by andreibondarev** [comment]
@nakedsushi What do you think of moving these out to env vars? https://github.com/ProjectResound/store-upload/blob/master/src/scripts/constants/api-urls.js#L2-L3

**Comment by nakedsushi** [comment]
Bumping this estimate to a 1 b/c I spent most of my time fighting dependency issues b/c of the babel & webpack upgrade.

**Comment by nakedsushi** [comment]
KPCC instance is on the :dev image. Gonna let it run till next week to make sure no bugs come up, then I'll release the change to :latest

**Comment by nakedsushi** [comment]
Updated `scprdev/resound-store-manage:latest` image and released to demo and kpcc instances.
