### ISSUE TITLE
Bug: Clicking on "See all your activity" does not show alert

### ISSUE THREAD

**Issue by nakedsushi** [ProjectLoudly/planning#168]
Steps to reproduce:

1. log into resound to get to the index page
1. add an audio file to the dropzone on the left
1. click "See all your activity" link at the top right
1. **BUG:** user immediately is redirected to the link instead of getting an alert/warning about navigating away

If a user has something in the dropzone and they click on anything that navigates away, there should be an alert that pops up warning them of unfinished business. To see an example of this, put something in the dropzone, then click on an uploaded audio that's in the right side of the explorer. An alert should pop up like this:

![Screen Shot 2018-10-17 at 1.56.42 PM.png](https://images.zenhubusercontent.com/57d22a42e40e5714b16e8f72/18b9a0b9-ad09-49e8-a661-1b824ea192f0)

AC:
- [x] a user is alerted when they click their activity link while there are still items in the dropzone
~~- [ ] there is a test for this~~
- [x] resound-store-upload docker image is updated

**Comment by jo-im** [comment]
I have successfully merged my fix to master and the resound-store-upload docker is updated. If there are any audio in the dropzone and the user clicks on "See all your activity" an alert should pop out warning that there is still an audio in the dropzone and if they would still like to leave the page. TestCafe couldn’t login successfully on my laptop, so Louise and I agreed to take the test portion off the ticket.

The commit that holds these changes are here:
https://github.com/ProjectResound/store-upload/commit/c208a5e4dba778a63d8ea73234edac195a8f2f4c
