### ISSUE TITLE
Lets users upload large files

### ISSUE THREAD

**Issue by nakedsushi** [ProjectLoudly/planning#17]
AC
- [ ] User can upload a file that's > 30 mins using Chrome

Currently, there's a bug in Chrome that just crashes the browser tab the uploader is in if a user tries to upload a file that's > 30 minutes long.  The crash is during the encoding process, so it never actually gets to uploading.

**Comment by nakedsushi** [comment]
Still no solution for this one. For some reason unknown to me, Chrome starts consuming a lot (100+%) of CPU and memory whenever the encoding workers starts up and the worker always crashes and burns after encoding 48% of a 1 hour segment.  In comparison, both Safari and Firefox stay at average CPU and memory usage and can process a file that large fine.  No reply yet on the issue I filed w/ the flac.js repo.

A couple of ways we can go with this:
1. Strongly suggest users use Safari or Firefox when using this tool
2. Re-write the encoding worker so that it splits the file to manageable chunks before encoding, encode it, stitch the file back together again and then upload it.  I'm not really sure how feasible this one is, but I'm estimating this would turn this ticket into at least a 5 for me to dive into the messy world of encoding and flac stitching.

**Comment by Ravenstine** [comment]
I don't know if you've already looked at this, but this _might_ help since it doesn't appear like Flac.js applies many settings to its Emscripten compilation.
https://github.com/kripken/emscripten/wiki/Chrome-Memory-Issues

**Comment by vsinghkpcc** [comment]
Closing in favor of https://github.com/ProjectLoudly/planning/issues/21 and https://github.com/ProjectLoudly/planning/issues/22
