### ISSUE TITLE
Encode file chunks

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#22]
AC
- [x] Uploader can encode file chunks
- [ ] Server can stitch together those chunks to produce the expected full file
- [ ] Instead of client encoding metadata, pass metadata to server for server to encode into stitched file
- [ ] `importScripts()` should not be doing multiple GETs of the same script.

**Comment by nakedsushi** [comment]
Closing this ticket since it looks like Flac does not support encoding arbitrary data, which means it can't really encode file chunks. I ran through a few files testing this out and it wasn't able to reliably encode any of the middle chunks when the audio file is bps=24.
