### ISSUE TITLE
Feature / Capability matrix for public

### ISSUE THREAD

**Issue by vsinghkpcc** [ProjectLoudly/planning#3]
AC
- [x] Finalize matrix prioritizing feature/capability areas
- [x] Add landscape analysis of common solutions/vendors for each area

**Comment by sdillingham** [comment]
Finalized matrix is here: https://docs.google.com/spreadsheets/d/153NWXadFuMpyrFqbTyEuH4oyH-yms_6PkoIcKRcn34g/edit#gid=0
