### ISSUE TITLE
Research and document audio metadata we want to store

### ISSUE THREAD

**Issue by sdillingham** [ProjectLoudly/planning#5]
AC:
- [x] Document metadata standards for common output formats: MP3, AAC, ~~OGG~~
- [x] Document metadata spec for podcast RSS items
- [ ] ~~Document metadata standards for NPR One~~
- [x] Meet and brainstorm other metadata we definitely/may want to store 
- [x] Compile into a single "metadata recommendations" document

**Comment by nakedsushi** [comment]
@sdillingham Can anyone upload to NPR One?  Not sure where to get the requirements for uploading to it.
