### ISSUE TITLE
Research DAAST standard and Triton/StreamGuys ad insertion tech

### ISSUE THREAD

**Issue by sdillingham** [ProjectLoudly/planning#6]
AC:
- [x] Participate in a conference call with Kyle Wesloh to demo APM/MPR's work on cue point metadata insertion, transcoding and Triton/Streamguys ad insertion metadata
- [x] Read up on the IAB DAAST specification (http://www.iab.com/wp-content/uploads/2015/12/DAAST_1.1-3.pdf)
- [x] Write up comments on this ticket documenting any important learning

**Comment by nakedsushi** [comment]
May not be applicable to us for the ad-stitching service we may one day build, but nice things to know:
- supports visual components for when they can actually be displayed
- supports skippable ads

Required of the ad server:
- should request tracking pixel at the appropriate time to notify ad server that an ad has been played (URI to notify server is in <Impression> element
- use info in <Error> elements to report playability errors back to ad server.

**Comment by sdillingham** [comment]
All great points @nakedsushi. FYI that our iPhone app (client side) and StreamMachine (server side) were updated earlier this year to support many of the DAAST features you mentioned.

**Comment by sdillingham** [comment]
Here's some of the relevant StreamMachine work:

https://github.com/StreamMachine/StreamMachine/blob/654ca02c4917e48ef8ac2c83fa67bd9d903fb2fb/src/streammachine/slave/preroller.coffee#L277

**Comment by chris-fuller** [comment]
And the iOS work:

https://github.com/SCPR/KPCC-iPhone/pull/132
https://github.com/SCPR/KPCC-iPhone/pull/131
https://github.com/SCPR/KPCC-iPhone/pull/148
https://github.com/SCPR/KPCC-iPhone/pull/169
