### ISSUE TITLE
Create a Digital Audio Workflow Template

### ISSUE THREAD

**Issue by nakedsushi** [ProjectLoudly/planning#7]
Using SCPR's completed workflow spreadsheet (https://docs.google.com/spreadsheets/d/153NWXadFuMpyrFqbTyEuH4oyH-yms_6PkoIcKRcn34g/edit#gid=0) as a guide, create a template that can be sent to other stakeholders for them to fill out.

AC:
- [ ] template exists in a format that stakeholders can edit

**Comment by vsinghkpcc** [comment]
Decided on alternate approach. Remain work in #8 .
