### ISSUE TITLE
Audio Player Waveform

### ISSUE THREAD

**Issue by nakedsushi** [ProjectLoudly/planning#97]
Resources:
https://github.com/SCPR/KPCC-audiogram/blob/master/audiogram/waveform.js
https://www.npmjs.com/package/waveform

AC:
- [x] there is a waveform of the sound file on the individual audio page
- [x] users can press 'play' to play the audio
- [x] users can press 'pause' to pause the audio
- [x] waveform reflects where in the audio the player is

**Comment by nakedsushi** [comment]
@tinykb thoughts on the waveform?

The comps have this, which I find hard to visually match up what's playing and what I'm looking at:
<img width="1065" alt="positiveY" src="https://user-images.githubusercontent.com/360040/29280716-389c5b3a-80d1-11e7-8792-c52ced2118e1.png">

What do you think about using a more traditional waveform like this:
<img width="1079" alt="screen shot 2017-08-14 at 9 15 00 am" src="https://user-images.githubusercontent.com/360040/29280749-58ba2bc2-80d1-11e7-80ea-34491af7354a.png">

I also made the pixel width 1 instead of 2 like in the comps b/c with 2, the resolution was too low and we were missing some of the peaks in audio, adding to the problem of pairing what I'm looking at and what I'm hearing.

**Comment by tinykb** [comment]
Your version looks good to me 👍

**Comment by nakedsushi** [comment]
In review: https://github.com/ProjectResound/store-upload/pull/6

**Comment by nakedsushi** [comment]
https://github.com/ProjectResound/store-upload/commit/4e8e57ec39efb9d1d7223905bf3ee6a8f291c279
